name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    if: github.event_name != 'release'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, macos-14, windows-2022 ]
        python: [ '3.10', '3.11', '3.12', '3.13' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: '**/pyproject.toml'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e '.[dev]'

      - name: Run pre-commit (format & hygiene)
        if: matrix.os == 'ubuntu-24.04' && matrix.python == '3.12'
        run: |
          python -m pip install pre-commit
          pre-commit run --all-files

      - name: Run tests
        run: pytest -q

  publish-pypi:
    name: Publish on PyPI
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build -s -w

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          packages-dir: dist
          verify-metadata: true
          attestations: true
          print-hash: true
          skip-existing: true
